import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import Navbar from "./Components/Navbar";
import "./globals.css";
import Footer from "./Components/Footer";
import LayoutWrapper from "./Components/LayoutWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
  className={`${inter.variable} ${playfair.variable} antialiased`}
> 
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
