import mongoose from 'mongoose';

const InvoiceSchema = new mongoose.Schema(
    {
      // ✅ الحقول الموجودة (لا تغيّرها)
      orderId: { type: mongoose.Schema.Types.ObjectId, ref: 'Order', index: true },
      orderNumber: { type: String, index: true },
      items: { type: Array, default: [] },
      subtotal: { type: Number },
      discount: { type: Number, default: 0 },
      shipping: { type: Number },
      total: { type: Number },
      currency: { type: String, default: 'gbp' },
      client: { type: Object },
      shippingAddress: { type: Object },
      billingAddress: { type: Object },
      paidAt: { type: Date },
      paymentIntentId: { type: String, index: true, sparse: true },
      
      sent: { type: Boolean, default: false },
      sentAt: { type: Date },
      sendError: { type: String },
      sender: { type: Object, default: null },
      recipientEmail: { type: String, default: '' },
      metadata: { type: Object, default: {} },
  
      // 🆕 الحقول الجديدة للفواتير اليدوية
      source: {
        type: String,
        enum: ['stripe', 'manual'],
        default: 'stripe',
        index: true,
      },
      
      paymentStatus: {
        type: String,
        enum: ['unpaid', 'paid', 'partial'],
        default: function() {
          return this.source === 'stripe' ? 'paid' : 'unpaid';
        },
      },
      
      dueDate: { type: Date },

      // Per-invoice opt-out for the automated reminder cron (app/api/cron/invoice-reminders) —
      // defaults true so every existing invoice keeps its current behavior; only invoices
      // explicitly created with reminders turned off skip the cron.
      remindersEnabled: { type: Boolean, default: true },

      notes: { type: String },

      couponName: { type: String, default: null },

      // Recurring invoice — set on a "template" manual invoice. The cron at
      // app/api/cron/recurring-invoices creates a brand-new Invoice (new invoice number, fresh
      // due date, unpaid) on the configured day of every month, cloning this one's client/items/
      // shipping/notes. Toggle `recurring.enabled` off to pause it without losing the config.
      recurring: {
        enabled: { type: Boolean, default: false },
        // 1-28 only — days 29-31 don't exist in every month, so capping at 28 keeps the
        // schedule identical every single month rather than drifting/skipping short months.
        dayOfMonth: { type: Number, min: 1, max: 28 },
        lastGeneratedAt: { type: Date },
      },
      // Set on invoices *generated by* the recurring cron, pointing back at the template
      // invoice they were cloned from — lets admin trace "why does this invoice exist".
      recurringSourceId: { type: mongoose.Schema.Types.ObjectId, ref: 'Invoice', index: true },
    },
    { timestamps: true }
  );

export default mongoose.models.Invoice || mongoose.model('Invoice', InvoiceSchema);